//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lr11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public string Namee { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Birthday_date { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string napravleniye { get; set; }
        public Nullable<int> kolvo_proizv { get; set; }
        public Nullable<System.DateTime> thefirstpublication { get; set; }
    }
}
